name: Amazon Linux

on:
    push:
        branches: [ main ]
        paths-ignore:
            - AUTHORS.md
            - CC-BY-4.0.txt
            - CHANGES.md
            - CODE_OF_CONDUCT.md
            - CONTRIBUTING.md
            - COPYING
            - COPYING.LIB
            - HISTORY
            - LICENSE-2.0.txt
            - MISSING
            - MIT.txt
            - README.md
            - RELEASE
            - TODO
            - 'contrib/**'
            - 'data/**'
            - 'doc/**'
            - 'po/**'
            - 'regress/**'

jobs:
    linux:
        # Use containers on their ubuntu latest image
        runs-on: ubuntu-latest

        # Necessary to run against older libraries
        # Amazon Linux can't use node20 for the checkout action
        steps:
            - name: Link node16 to node20
            - run: |
                  cd $RUNNER_HOME/actions-runner/externals
                  mv node20 node20.orig
                  ln -s node16 node20

        # Set up the matrix of distributions to test
        strategy:
            matrix:
                container: ["amazonlinux:2"]

        container:
            image: ${{ matrix.container }}

        # All of these steps run from within the main source
        # directory, so think of that as your $PWD
        steps:
            # Requirements before the git clone can happen
            - name: git clone requirements
              run: |
                  amazon-linux-extras install epel -y
                  yum install -y git

            # This means clone the git repo
            - uses: actions/checkout@v2

            # Within the container, install the dependencies, build,
            # and run the test suite
            - name: Build and run the test suite
              run: |
                  # Install make(1) so we can use the instreqs target
                  yum install -y make

                  # Install build dependencies and set up the target
                  make instreqs

                  # Build the software and run the test suite
                  make debug
                  make check
                  ninja -C build coverage && ( curl -s https://codecov.io/bash | bash ) || :
